/**
 * Generates Asterisk PJSIP configuration from user settings.
 * Writes pjsip.conf so Asterisk can register as a SIP extension with 3CX.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as dns from 'dns';
import { execFile } from 'child_process';
import { promisify } from 'util';
import { CONFIG } from './config';
import { getSetting } from './db';

const execFileAsync = promisify(execFile);
const dnsLookup = promisify(dns.lookup);

interface SipSettings {
  pbxHost: string;
  sipPort: number;
  extension: string;
  authId: string;
  password: string;
  transport: 'udp' | 'tls';
}

/** Read SIP settings from DB. Returns null if not fully configured. */
export function getSipSettings(): SipSettings | null {
  const pbxUrl = getSetting('pbx_url');
  const extension = getSetting('sip_extension');
  const password = getSetting('sip_password');

  if (!pbxUrl || !extension || !password) return null;

  // Extract host from URL
  const pbxHost = pbxUrl.replace(/^https?:\/\//, '').replace(/\/+$/, '');
  const transport = (getSetting('sip_transport') || 'udp') as 'udp' | 'tls';
  const defaultPort = transport === 'tls' ? '5061' : '5060';
  const sipPort = parseInt(getSetting('sip_port') || defaultPort, 10);
  // Auth ID defaults to extension if not set (3CX uses a separate Auth ID)
  const authId = getSetting('sip_auth_id') || extension;

  return { pbxHost, sipPort, extension, authId, password, transport };
}

/** Generate and write pjsip.conf for Asterisk. */
export async function writePjsipConfig(settings: SipSettings): Promise<void> {
  const { pbxHost, sipPort, extension, authId, password, transport } = settings;

  const useTls = transport === 'tls';
  const transportName = useTls ? 'transport-tls' : 'transport-udp';

  // For TLS, resolve hostname to IP — PJSIP's internal DNS resolver fails with
  // NAPTR/SRV lookups on cloud PBXes. Using IP directly fixes this.
  let serverHost = pbxHost;
  if (useTls) {
    try {
      const result = await dnsLookup(pbxHost);
      serverHost = result.address;
      console.log(`[AsteriskConfig] Resolved ${pbxHost} → ${serverHost}`);
    } catch (err) {
      console.warn(`[AsteriskConfig] DNS resolve failed for ${pbxHost}, using hostname:`, err);
    }
  }

  // Build transport section
  let transportSection: string;
  if (useTls) {
    transportSection = `; ── Transport (TLS) ──
[${transportName}]
type = transport
protocol = tls
bind = 0.0.0.0:5061
method = tlsv1_2
ca_list_file = /etc/ssl/certs/ca-certificates.crt
allow_wildcard_certs = yes
`;
  } else {
    transportSection = `; ── Transport (UDP) ──
[${transportName}]
type = transport
protocol = udp
bind = 0.0.0.0:${sipPort}
`;
  }

  const transportParam = useTls ? '\\;transport=tls' : '';

  const config = `; Auto-generated by 3CX Auto-Pager — do not edit manually
; Generated: ${new Date().toISOString()}

${transportSection}
; ── Authentication ──
[3cx-auth]
type = auth
auth_type = userpass
username = ${authId}
password = ${password}

; ── Address of Record ──
[3cx-aor]
type = aor
contact = sip:${serverHost}:${sipPort}${transportParam}
qualify_frequency = 60

; ── Registration with 3CX PBX ──
[3cx-registration]
type = registration
transport = ${transportName}
outbound_auth = 3cx-auth
server_uri = sip:${serverHost}:${sipPort}${transportParam}
client_uri = sip:${extension}@${pbxHost}
contact_user = ${extension}
retry_interval = 30
expiration = 3600

; ── Endpoint for outbound calls ──
[3cx-endpoint]
type = endpoint
transport = ${transportName}
context = from-3cx
disallow = all
allow = ulaw
allow = alaw
outbound_auth = 3cx-auth
aors = 3cx-aor
from_user = ${extension}
from_domain = ${pbxHost}

; ── Identify incoming from 3CX ──
[3cx-identify]
type = identify
endpoint = 3cx-endpoint
match = ${serverHost}
`;

  // Copy template configs if not already present
  const asteriskDir = CONFIG.asteriskConfigDir;
  const templatesDir = '/etc/asterisk-templates';

  // Copy base configs from templates (manager.conf, modules.conf, extensions.conf)
  if (fs.existsSync(templatesDir)) {
    for (const file of ['manager.conf', 'modules.conf', 'extensions.conf']) {
      const src = path.join(templatesDir, file);
      const dst = path.join(asteriskDir, file);
      if (fs.existsSync(src) && !fs.existsSync(dst)) {
        fs.copyFileSync(src, dst);
      }
    }
  }

  // Write pjsip.conf
  const pjsipPath = path.join(asteriskDir, 'pjsip.conf');
  fs.writeFileSync(pjsipPath, config, 'utf-8');
  console.log(`[AsteriskConfig] Wrote ${pjsipPath}`);
}

/** Reload Asterisk PJSIP module (if Asterisk is running). */
export async function reloadAsterisk(): Promise<boolean> {
  try {
    await execFileAsync('asterisk', ['-rx', 'pjsip reload']);
    console.log('[AsteriskConfig] Asterisk PJSIP reloaded');
    return true;
  } catch (err) {
    console.warn('[AsteriskConfig] Asterisk reload failed (may not be running):', err);
    return false;
  }
}

/** Check if Asterisk is running. */
export async function isAsteriskRunning(): Promise<boolean> {
  try {
    await execFileAsync('asterisk', ['-rx', 'core show version']);
    return true;
  } catch {
    return false;
  }
}

/** Get Asterisk SIP registration status. */
export async function getRegistrationStatus(): Promise<string> {
  try {
    const { stdout } = await execFileAsync('asterisk', [
      '-rx',
      'pjsip show registrations',
    ]);
    return stdout.trim();
  } catch {
    return 'Asterisk not running';
  }
}
